package projecteuler;

import static utils.IteratorFunctionalUtils.fibonacciNumbersLessThan;

import java.util.Iterator;

public class Problem2 extends EulerProblem{

	public void solution() {

		long sum = 0;
		Iterator<Long> iterator = fibonacciNumbersLessThan(4000000);
		
		while(iterator.hasNext()) {
			Long next = iterator.next();
			sum = (next % 2 == 0) ? (sum + next) : sum; 
		}
	
		System.out.println(sum);
	}

	@Override
	public String problemDescription() {
		return "Each new term in the Fibonacci sequence is generated by adding the previous two terms.\n" + 
				"By starting with 1 and 2, the first 10 terms will be:\n" + 
				"1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..." + 
				"By considering the terms in the Fibonacci sequence whose values do not exceed four million," +  
				"find the sum of the even-valued terms.";
	}
	
}
